#!/usr/bin/env bash

echo ""
toilet -f smblock --filter metal 'NixOS  Flake  Rebuild'

echo ""
git diff

# Commit su Github
git add .
echo -ne "\033[4;32mInserisci messaggio del commit:\033[0m " # Testo con ANSI
read -r commit_message
git commit -m "$commit_message"

if [ "$1" == "-push" ]; then
  git push
  shift 1
fi

# Rebuild sistema
sudo nixos-rebuild switch --flake /Nixos/#"$1"
