{
  imports = [
    #./freshrss.nix
    ./frigate.nix
    ./gramps.nix
    ./headscale.nix
    ./home-assistant.nix
    ./immich.nix
    ./ionos-ddns.nix 
    ./mosquitto.nix
    ./navidrome.nix
    #./nextcloud.nix
    #./nfs.nix
    ./podman.nix
    ./searx.nix
    ./tailscale.nix
    ./tandoor.nix
    ./traefik.nix
  ];
}
